### ISSUE TITLE
Cant use google account

### ISSUE THREAD

**Issue by kichawa** [arcao/Geocaching4Locus#125]
when i tried to log via google account there was:

Error403: disallowed_useragent

**Comment by arcao** [comment]
Fixed in version 3.0.6.

**Comment by kichawa** [comment]
There is another problem. When I've tried to log in I should complete setup and click "agree" button. Then I've got "Autorization success". When i clicked on "Return back to application" button there is a popup with "the autorization code is invalid".

Manually i can't paste the autorozation code. The only way i should retype it :(
