### ISSUE TITLE
Import list no longer works (endless waiting circle)

### ISSUE THREAD

**Issue by Keksbande65** [arcao/Geocaching4Locus#136]
**Describe the bug**
Geocaching/Import List show endless waiting circle instead of overview of all lists, which are available on my geocaching account.

**To Reproduce**
I call the 3rd party feature "Geocaching/Import Lists".
Instead of the overview of all lists, which I could import, I get an endless waiting circle. 
I have reduced the number of lists in my account, just to be on the safe side, but this did not change anything.
I cannot say for sure when it worked last, but I would say that about 2 weeks ago I could still use it successfully.
Could the problem be somehow connected to the changes in the pocket query API, which were published recently?

**Expected behavior**
Overview of all lists available on my geocaching account is displayed.

**Screenshots**

**Smartphone (please complete the following information):**
Cyrus CX45XA
Android 9

**Additional context**
Locus Version 4.12.1
UserID 106d6ebd7
GC4L Version 3.0.8

I posted this in https://forum.locusmap.eu/index.php?topic=8195.0 and was told to address it here.

![Screenshot_20221103-194005](https://user-images.githubusercontent.com/117466364/200014897-b2e13331-7196-4df3-a959-c1e3bd852ccf.png)

**Comment by arcao** [comment]
Fixed.
