### ISSUE TITLE
Add support for OKAPI (for OpenCaching National Sites)

### ISSUE THREAD

**Issue by wrygiel** [arcao/Geocaching4Locus#29]
Currently there are 4 opencaching sites which use OKAPI:
- OpenCaching.PL - http://opencaching.pl/okapi/
- OpenCaching.US - http://www.opencaching.us/okapi/
- OpenCaching.NL - http://www.opencaching.nl/okapi/
- OpenCaching.ORG.UK - http://www.opencaching.org.uk/okapi/
- and more are coming (i.e. OpenCaching.DE).

It's hard to say without knowing the code, but I believe it _might_ be easy to add support for OKAPI in your extension. All opencaching sites use exactly the same API, and it is well documented (see any of the sites above).

So, my questions are:
1. Did you ever plan to support multiple geocaching sites in your extension?
2. If your architecture was designed for one data-source only, then would it be easier to fork your project and _replace_ the data-source, rather than adding support for multiple data sources? What do you think?
3. If you think [2] would be relatively easy, would it be okay if I forked your repository and tried to do that? (There's only a minor chance I will have time to finish this, but I would like to have your permission before I even try.)
4. Or, perhaps, if the answer to [1] is yes, then maybe you would be interested in supporting OKAPI in your mainstream branch? I am the main developer of OKAPI, so in case of any problems, I could add any methods you may require.

In case you didn't hear about OC - OpenCaching National Sites are NOT affiliated with opencaching.com (which is a Garmin initiative). We are opensource and much older than OC.com.

**Comment by arcao** [comment]
This will be implemented as a separate add-on. See here: https://github.com/arcao/Opencaching4Locus
