### ISSUE TITLE
Delete cache after upload field notes - (feature?)

### ISSUE THREAD

**Issue by busty03** [arcao/Geocaching4Locus#36]
it will be fine to have some check-box in settings to synchronize delete upload notes and delete geocache from device or at minimum unmark it from viewed caches

**Comment by Hadatko** [comment]
I would like to do 1 propose. I can do it :D

**Comment by arcao** [comment]
This has to be done on Locus Map side, because sending the field notes is done in Locus Map. Thus please create request at [Locus Map helpdesk](http://help.locusmap.eu/).
