### ISSUE TITLE
Change cache count back to text

### ISSUE THREAD

**Issue by risototh** [arcao/Geocaching4Locus#40]
Please change the "cache count" for download back to simple text or slider. This list is not very comfortable.
![2013-04-16 10 20 23](https://f.cloud.github.com/assets/800331/384969/adef9178-a66e-11e2-9d64-070970aadd2c.png)

**Comment by arcao** [comment]
In upcoming version 2.0 is it implemented differently (commit ed33127e12d568de543d04c635731eacabd716fc)
