### ISSUE TITLE
can you send me old version of G4L

### ISSUE THREAD

**Issue by Phoenicurus** [arcao/Geocaching4Locus#59]
Dobrý den,
nedávno jsem si aktualizoval Locus PRO a geocaching4locus na nejnovější verzi. Bohužel, můj starý telefon nový LocusPRO nezvládá a aplikace mi často padá. Poprosil jsem tedy vývojáře o zaslání starší verze, která byla v mém telefonu stabilní (v. 3.0.2) a rád bych poprosil i Vás, jestli byste byli tak hodní a poslali mi starší verzi G4L. Rád Vám za to něco zaplatím. 
Díky a hezký den.
Ondřej Švec

My english is terrible, I am sorry:
Hello,
I recently updated Locus PRO and geocaching4locus to new version. Unfortunately, Locus does not work in my old phone. So I asked "Locus help" to send my older version that was on my phone stable (v. 3.0.2) and I would like to ask you also, if you would be so kind as to send me an older version G4L. New version of Geocaching4locus (with old version of Locus) does not allow downloading geocaches.... I will gladly pay for something. 
Thanks for understanding and have a nice day.
Andrew Svec
c.evsjerdno(@) gmail.com

**Comment by arcao** [comment]
Ahoj,
Poslední verzi pro Locus Map 3.0.2 si můžeš stáhnout odsud: http://geocaching4locus.eu/download#toc-latest-version-for-android-2-x-devices

Je to ta verze add-onu 1.5.7.1.
