### ISSUE TITLE
Addon don't save cache url

### ISSUE THREAD

**Issue by ormoru** [arcao/Geocaching4Locus#60]
Addon dont save cache url
mCacheUrl = http://www.geocaching.com/seek/cache_details.aspx?guid=GUID.

**Comment by arcao** [comment]
Hi,

Could you please post your not working url? Because bellow url works OK:

http://www.geocaching.com/seek/cache_details.aspx?guid=793d0999-a667-405a-b530-4339ee488ac8

**Comment by ormoru** [comment]
Hi,
 yes, url works ok. But save G4L addon this url into Locus? I think, that no. I talked with Menion and Locus dont download cache directly. And I have this url in the waypoint, if I import PQ, but not, if I download cache by addon.
Is it a problem add this value into the waypoint? I'd like to do vote for GCVote, but for voting I must know GUID not GC Code. And users, which download cache by addon, will not be able to vote.

Thanks a lot
Jarda

**Comment by arcao** [comment]
Hi,

Yes, the import geocache from a website link is supported by add-on. See this page in a manual: http://geocaching4locus.eu/manual/importing-caches#toc-import-from-link

**Comment by ormoru** [comment]
No, we do not understand :) Addon of course listen for this url, but dont save this URL into waipont.

If I import cache from PQ and call mLocusWaypoint.gcData.getCacheUrl(), I get this String "http://www.geocaching.com/seek/cache_details.aspx?guid=793d0999-a667-405a-b530-4339ee488ac8"

If I import cache via addon and call mLocusWaypoint.gcData.getCacheUrl(), I get empty String.


Would you please support cacheUrl in the [Geocache.java](https://github.com/arcao/geocaching-api/blob/master/src/main/java/com/arcao/geocaching/api/data/Geocache.java) file and save this url in cache waypoint? I like add function for vote in GCVote system and I need guid, which is in url only. Otherwise users used this addon cant use this function.

Thanks a lot
Jarda

**Comment by arcao** [comment]
No problem.

**Comment by arcao** [comment]
Implemented.
