### ISSUE TITLE
Recognition dnf caches

### ISSUE THREAD

**Issue by Hadatko** [arcao/Geocaching4Locus#79]
This can be usefull in situations when somebody is on on-day trip somewhere in long distance. He don't want looking for caches with dnf.

I can do this feature in locus.

**Comment by Hadatko** [comment]
Thanks

**Comment by arcao** [comment]
I re-implemented with extended configuration and support for updating geocaches and logs. There still missing additional check when **how many last logs to check** is lower than **count of logs to download** in preference activity. I think it should show some error message. Also when user change **how many last logs to check** it should increase **count of logs to download**.

**Comment by arcao** [comment]
Added value checking to prevent not working situations.
