### ISSUE TITLE
Import attachments to cache automatically

### ISSUE THREAD

**Issue by thedragon013** [arcao/Geocaching4Locus#87]
Hello,

maybe I missed this feature but I wondered if there is an option to automatically add attachments to a cache. As far as I can see, you have to open a listing, scroll to the tab "attachments" and there you can choose files or images to attach to that listing. That's ok, if there is only 1 or 2 files. But for a whole bunch is quite painful. So I wondered if there is a way to store the files into a special structure (like for the images in a listing) and the attachment tab recognizes these files. 

Also the naming of the attachments you add during caching (the pictures you take for example) could be stored there and sorted by GCCode. 

If there is such a feature already, I would be glad if someone could point it out for me. If not, I would like to open a feature request. 

In any case: thanks a bunch for that great tool!

Dragon013

**Comment by arcao** [comment]
This is Locus Map feature request, please create request here: http://help.locusmap.eu/
