### ISSUE TITLE
Problem with Locus Map Free & Pro on single device

### ISSUE THREAD

**Issue by menion** [arcao/Geocaching4Locus#91]
**Description**:
On device, where both versions of Locus Map are installed, add-on not everytime use correct, active, version of application. Most visible it's for example for update of cache logs, where sometimes are logs updated over second application so UI is not refreshed.

**Reason**:
I've found serious issue in Locus API 0.2.10 , where [call for active version](https://github.com/asamm/locus-api/blob/8b919bda12964324c681db3b744ce1cea29c5f50/locus-api-android/src/main/java/locus/api/android/utils/LocusUtils.java#L300), returned "random version" because value '0' caused ignoring of really active version.

**Solution**:
a) update to new Locus API version 0.2.11
b) use function LocusUtils.getActiveVersion(context, VersionCode.UPDATE_11)

Using both solutions at once is recommended.

**Comment by arcao** [comment]
Updated to Locus API version 0.2.11 in 0aedeb9eac44e8dd40d47d532ced36f536bd9d7f.

**Comment by arcao** [comment]
Done
