### ISSUE TITLE
Switch to new Geocaching API v1

### ISSUE THREAD

**Issue by arcao** [arcao/Geocaching4Locus#96]
Groundspeak introduced [new Geocaching API](https://api.groundspeak.com/documentation).

Replace old API with new one.

Breaking changes:
* Excluding searching geocaches that are on ignore list is not supported. There is [no filter for this](https://api.groundspeak.com/documentation#query-filters).

**Comment by DieBatzen** [comment]
Hi Arcao,

since the old Groundspeak API will soon be retired, may I ask if you still plan to switch to the new one?
That would be awesome.
